"""initial schema

Revision ID: 7436359d2d5b
Revises: 
Create Date: 2026-09-09 15:07:54.126192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7436359d2d5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses')),
    sa.UniqueConstraint('name', name=op.f('uq_statuses_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'user'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('service_requests',
    sa.Column('requestor_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('request_type', sa.String(length=50), server_default=sa.text("'general'"), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('current_status_id', sa.UUID(), nullable=False),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name=op.f('ck_service_requests_priority_valid')),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_service_requests_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_status_id'], ['statuses.id'], name=op.f('fk_service_requests_current_status_id_statuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requestor_id'], ['users.id'], name=op.f('fk_service_requests_requestor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_requests'))
    )
    op.create_index(op.f('ix_service_requests_assignee_id'), 'service_requests', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_service_requests_current_status_id'), 'service_requests', ['current_status_id'], unique=False)
    op.create_index(op.f('ix_service_requests_requestor_id'), 'service_requests', ['requestor_id'], unique=False)
    op.create_table('comments',
    sa.Column('service_request_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], name=op.f('fk_comments_service_request_id_service_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_service_request_id'), 'comments', ['service_request_id'], unique=False)
    op.create_table('status_history',
    sa.Column('service_request_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_status_history_changed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], name=op.f('fk_status_history_service_request_id_service_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_status_history_status_id_statuses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_history'))
    )
    op.create_index(op.f('ix_status_history_service_request_id'), 'status_history', ['service_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_service_request_id'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_comments_service_request_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_service_requests_requestor_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_current_status_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_assignee_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    op.drop_table('statuses')
    # ### end Alembic commands ###
