"""chat conversations and messages

The two tables the chat assistant needs (specs/chatbot/design.md §6, T-CHAT-0),
and no others. In particular **no FAQ table**: CHAT-12 keeps that content in a
version-controlled module (``app/chat/faq.py``), so it is reviewed and rolled
back with the code that reads it rather than edited in a database where nobody
sees the change.

Two details worth not "correcting" later:

* ``chat_conversations.user_id`` is UNIQUE, not merely indexed. One continuous
  conversation per user is decision 2, and the constraint is what makes the
  get-or-create in ``app/chat/conversation.py`` safe against two messages sent
  at once — without it, a race produces two rows and splits a user's history.
* ``chat_messages.created_at`` defaults to ``clock_timestamp()`` rather than
  the ``now()`` every other table here uses. ``now()`` is
  ``transaction_timestamp()`` and does not advance within a transaction; this
  is the one table that appends several rows per unit of work, and CHAT-10
  needs them back in the order they were written. The model file carries the
  full reasoning.

Revision ID: 777a0f2c4778
Revises: 80919378ee7a
Create Date: 2026-09-14 22:53:20.287267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '777a0f2c4778'
down_revision: Union[str, Sequence[str], None] = '80919378ee7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_conversations')),
    sa.UniqueConstraint('user_id', name=op.f('uq_chat_conversations_user_id'))
    )
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_chat_messages_role_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('fk_chat_messages_conversation_id_chat_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
