"""seed statuses reference data

Data migration (not autogenerated). Kept as its own revision, immediately
following the initial-schema revision, rather than folded into it, so the
schema revision stays a pristine ``alembic revision --autogenerate`` output
that can be regenerated during review without losing hand-written seed code.

Seeds the four ``statuses`` rows required by R3 / design.md:

    open        sort 1  is_terminal = false
    in_progress sort 2  is_terminal = false
    resolved    sort 3  is_terminal = true
    closed      sort 4  is_terminal = true

``id`` is omitted from the insert on purpose: the column carries a
``gen_random_uuid()`` server default, and design.md's resolved decision #3
deliberately does not pin fixed literal UUIDs for these rows.

Revision ID: 80919378ee7a
Revises: 7436359d2d5b
Create Date: 2026-09-09 13:46:57.930493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80919378ee7a'
down_revision: Union[str, Sequence[str], None] = '7436359d2d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Ad-hoc lightweight table for the data migration — intentionally not the ORM
# model, so this revision stays pinned to the schema as it existed here.
statuses_table = sa.table(
    "statuses",
    sa.column("name", sa.String),
    sa.column("sort_order", sa.Integer),
    sa.column("is_terminal", sa.Boolean),
)

SEED_ROWS = [
    {"name": "open", "sort_order": 1, "is_terminal": False},
    {"name": "in_progress", "sort_order": 2, "is_terminal": False},
    {"name": "resolved", "sort_order": 3, "is_terminal": True},
    {"name": "closed", "sort_order": 4, "is_terminal": True},
]


def upgrade() -> None:
    """Insert the four reference statuses."""
    op.bulk_insert(statuses_table, SEED_ROWS)


def downgrade() -> None:
    """Remove the four reference statuses."""
    op.execute(
        statuses_table.delete().where(
            statuses_table.c.name.in_([row["name"] for row in SEED_ROWS])
        )
    )
